version: '2'
services:
  db_data:
    image: busybox:latest
    command: "true"
    volumes: 
        - /spare/local/mariadb:/var/lib/mysql

  db: 
    image: mariadb:10.1.12
    restart: always
    volumes_from: 
        - db_data
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_USER=mariadb_user
        - MYSQL_PASSWORD=testpassword
        - MYSQL_DATABASE=towerportal

  redis:
     image: redis:3.0.7
     restart: always
     ports:
        - "6379:6379"

  web:
    build: .
    command: bash /code/.docker/web_entrypoint.sh
    volumes:
        - .:/code
    ports:
        - "8000:8000"
        - "8012:8012"
    depends_on:
        - redis
        - db

  celery_worker:
    build: .
    command: bash -c "sleep 3 && celery -A movie_db worker -l info"
    depends_on:
        - redis
